# Generated by Django 2.1.5 on 2021-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='recommend_list',
            field=models.ManyToManyField(blank=True, null=True, to='movie.RecommendList'),
        ),
    ]
