# Generated by Django 2.1.5 on 2021-08-01 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210801_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendlist',
            name='recommend_reason',
            field=models.CharField(default='', help_text='Title', max_length=10240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
