# Generated by Django 2.1.5 on 2021-08-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210801_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='recommend_list',
        ),
        migrations.AddField(
            model_name='recommendlist',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Movie'),
        ),
    ]
