# Generated by Django 2.1.5 on 2021-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20210804_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendlist',
            name='movie',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Movie'),
        ),
    ]
